title: Alethe
description: Flexible, SMT-LIB Native Proofs
theme: just-the-docs

url: https://alethe-proofs.github.io

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
