name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Checkout AletheInEunoia repo
        uses: actions/checkout@v4
        with:
          repository: cvc5/AletheInEunoia
          path: _external/AletheInEunoia
      - name: Copy external documentation
        run: cp -r _external/AletheInEunoia/docs/ ./AletheInEunoia
      - name: Download latest specification PDF
        env:
          GH_TOKEN: ${{ secrets.ALETHE_SPEC_TOKEN }}
        run: |
          RUN_ID=$(gh run list \
            --repo alethe-proofs/specification \
            --json databaseId,status,conclusion \
            -b main -L 1 \
            --jq '.[] |  select(.conclusion == "success" and .status == "completed") .databaseId')
          gh run download ${RUN_ID} \
            --repo alethe-proofs/specification
          mv artifact/doc.pdf specification.pdf
      - name: Build with Jekyll
        run: bundle exec jekyll build -V
